name: spotify_clone
description: A Spotify Clone.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.3+1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/spotify_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon_launcher_adaptive_fore.png"

flutter_native_splash:
  color: "#121212"
  image: "assets/icons/spotify_icon.png"
  android: true
  ios: true

flutter:
  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/gotham_font/GothamBold.ttf
          style: italic

    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
  uses-material-design: true
  assets:
     - assets/icons/spotify_logo_white.png
     - assets/background/home_screen_bg.png
     - assets/icons/bell.png
     - assets/icons/history.png
     - assets/icons/settings.png
     - assets/playlists/ordem_para_desc_album.jpeg
     - assets/playlists/queen_logo.jpg
     - assets/background/playlist_bg.png
     - assets/collections/ed_sheeran.png
     - assets/collections/beatles_abbey_road.jpg
     - assets/collections/led_zeppelin_stairway_to_heaven.jpg
     - assets/background/search_bg.png
     

